bind_addr = ":8020"
log_level = "debug"
database_url = "host=localhost dbname=restapi_dev sslmode=disable user=dev password=dev"
session_key = "1238216478662354642362345452dfhkjdfjkkvbkjdfdvbdjbhbhjvbfhbvfhbjfhbg"